# Generated by Django 6.0.1 on 2026-01-08 18:40

from django.db import migrations
import bcrypt


def create_test_users(apps, schema_editor):
    """Create test users with roles."""
    User = apps.get_model('authentication', 'User')
    Role = apps.get_model('authorization', 'Role')
    UserRole = apps.get_model('authorization', 'UserRole')
    
    # Get roles
    admin_role = Role.objects.get(name='admin')
    user_role = Role.objects.get(name='user')
    moderator_role = Role.objects.get(name='moderator')
    
    # Create admin user
    admin_password = "Admin123"
    admin_hash = bcrypt.hashpw(admin_password.encode(), bcrypt.gensalt(rounds=12)).decode()
    admin_user, _ = User.objects.get_or_create(
        email='admin@example.com',
        defaults={
            'first_name': 'Admin',
            'last_name': 'User',
            'password_hash': admin_hash,
            'is_active': True,
        }
    )
    UserRole.objects.get_or_create(user=admin_user, role=admin_role)
    
    # Create regular user
    user_password = "User123"
    user_hash = bcrypt.hashpw(user_password.encode(), bcrypt.gensalt(rounds=12)).decode()
    regular_user, _ = User.objects.get_or_create(
        email='user@example.com',
        defaults={
            'first_name': 'Regular',
            'last_name': 'User',
            'password_hash': user_hash,
            'is_active': True,
        }
    )
    UserRole.objects.get_or_create(user=regular_user, role=user_role)
    
    # Create moderator user
    mod_password = "Mod123"
    mod_hash = bcrypt.hashpw(mod_password.encode(), bcrypt.gensalt(rounds=12)).decode()
    moderator_user, _ = User.objects.get_or_create(
        email='moderator@example.com',
        defaults={
            'first_name': 'Moderator',
            'last_name': 'User',
            'password_hash': mod_hash,
            'is_active': True,
        }
    )
    UserRole.objects.get_or_create(user=moderator_user, role=moderator_role)


def remove_test_users(apps, schema_editor):
    """Remove test users (reverse migration)."""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(
        email__in=['admin@example.com', 'user@example.com', 'moderator@example.com']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('authorization', '0002_seed_roles'),
    ]

    operations = [
        migrations.RunPython(create_test_users, remove_test_users),
    ]
