# Generated by Django 6.0.1 on 2026-01-08 18:36

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default roles."""
    Role = apps.get_model('authorization', 'Role')
    
    roles = [
        {
            'name': 'admin',
            'description': 'System administrator with full access to all resources',
        },
        {
            'name': 'user',
            'description': 'Standard user with basic read access',
        },
        {
            'name': 'moderator',
            'description': 'Content moderator with read and write access',
        },
        {
            'name': 'guest',
            'description': 'Guest user with limited read-only access',
        },
    ]
    
    for role_data in roles:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={'description': role_data['description']},
        )


def remove_default_roles(apps, schema_editor):
    """Remove default roles (reverse migration)."""
    Role = apps.get_model('authorization', 'Role')
    Role.objects.filter(name__in=['admin', 'user', 'moderator', 'guest']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, remove_default_roles),
    ]
