# Generated by Django 6.0.1 on 2026-01-08 18:37

from django.db import migrations


def create_business_elements(apps, schema_editor):
    """Create default business elements."""
    BusinessElement = apps.get_model('authorization', 'BusinessElement')
    
    elements = [
        {
            'name': 'users',
            'description': 'User accounts management',
        },
        {
            'name': 'documents',
            'description': 'Document management system - create, view, edit, delete documents',
        },
        {
            'name': 'projects',
            'description': 'Project management system',
        },
        {
            'name': 'orders',
            'description': 'Order management system',
        },
        {
            'name': 'shops',
            'description': 'Shop management system',
        },
        {
            'name': 'products',
            'description': 'Product catalog management',
        },
    ]
    
    for element_data in elements:
        BusinessElement.objects.get_or_create(
            name=element_data['name'],
            defaults={'description': element_data['description']},
        )


def remove_business_elements(apps, schema_editor):
    """Remove business elements (reverse migration)."""
    BusinessElement = apps.get_model('authorization', 'BusinessElement')
    BusinessElement.objects.filter(
        name__in=['users', 'documents', 'projects', 'orders', 'shops', 'products']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_seed_roles'),
    ]

    operations = [
        migrations.RunPython(create_business_elements, remove_business_elements),
    ]
