# Generated by Django 6.0.1 on 2026-01-08 18:38

from django.db import migrations


def create_access_rules(apps, schema_editor):
    """Create default access rules."""
    Role = apps.get_model('authorization', 'Role')
    BusinessElement = apps.get_model('authorization', 'BusinessElement')
    AccessRoleRules = apps.get_model('authorization', 'AccessRoleRules')
    
    # Get roles
    admin_role = Role.objects.get(name='admin')
    user_role = Role.objects.get(name='user')
    moderator_role = Role.objects.get(name='moderator')
    guest_role = Role.objects.get(name='guest')
    
    # Get elements
    users_element = BusinessElement.objects.get(name='users')
    documents_element = BusinessElement.objects.get(name='documents')
    projects_element = BusinessElement.objects.get(name='projects')
    
    # Admin: Full permissions on all elements
    admin_permissions = {
        'read_permission': True,
        'read_all_permission': True,
        'create_permission': True,
        'update_permission': True,
        'update_all_permission': True,
        'delete_permission': True,
        'delete_all_permission': True,
    }
    
    for element in [users_element, documents_element, projects_element]:
        AccessRoleRules.objects.get_or_create(
            role=admin_role,
            element=element,
            defaults=admin_permissions,
        )
    
    # User: Read-only on documents and projects
    user_permissions = {
        'read_permission': True,
        'read_all_permission': True,
        'create_permission': False,
        'update_permission': False,
        'update_all_permission': False,
        'delete_permission': False,
        'delete_all_permission': False,
    }
    
    AccessRoleRules.objects.get_or_create(
        role=user_role,
        element=documents_element,
        defaults=user_permissions,
    )
    
    AccessRoleRules.objects.get_or_create(
        role=user_role,
        element=projects_element,
        defaults=user_permissions,
    )
    
    # Moderator: Read/write on documents and projects
    moderator_permissions = {
        'read_permission': True,
        'read_all_permission': True,
        'create_permission': True,
        'update_permission': True,
        'update_all_permission': True,
        'delete_permission': False,
        'delete_all_permission': False,
    }
    
    AccessRoleRules.objects.get_or_create(
        role=moderator_role,
        element=documents_element,
        defaults=moderator_permissions,
    )
    
    AccessRoleRules.objects.get_or_create(
        role=moderator_role,
        element=projects_element,
        defaults=moderator_permissions,
    )
    
    # Guest: Read-only on documents
    guest_permissions = {
        'read_permission': True,
        'read_all_permission': False,
        'create_permission': False,
        'update_permission': False,
        'update_all_permission': False,
        'delete_permission': False,
        'delete_all_permission': False,
    }
    
    AccessRoleRules.objects.get_or_create(
        role=guest_role,
        element=documents_element,
        defaults=guest_permissions,
    )


def remove_access_rules(apps, schema_editor):
    """Remove access rules (reverse migration)."""
    AccessRoleRules = apps.get_model('authorization', 'AccessRoleRules')
    AccessRoleRules.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_seed_business_elements'),
    ]

    operations = [
        migrations.RunPython(create_access_rules, remove_access_rules),
    ]
